Ext.define('B.store.SMailAddrInput',{
	extend:'Ext.data.Store',
	storeId:'SMailAddrInput',
	data:{'items':[]},
	model:'B.view.apps.mail.MMailAddrInput',
	proxy:{
		type:'memory',
		reader:{
			type:'json',
			rootProperty:'items'
		}
	}
}); 
