Ext.define('B.view.apps.mail.VMail',{
	extend:'Ext.panel.Panel',
	requires:[
		'B.view.apps.mail.MailController'
	],
	controller:'mail',
	alias:'widget.VMail',
	layout:'border',
	items:[
		{
			xtype:'VMailTree',
			region:'west',
			width:200,
			minWidth:100,
			maxWidth:300,
			split:true
		},
		{
			xtype: 'panel',
			id:'panel_mail_content',
			region:'center',
			layout:'fit',
			items:[{
				xtype:'VMailInbox'
			}]
		},{
			xtype:'panel',
			id:'panel_mail_compose',
			region:'south',
			split:true,
			collapsible:true,
			collapsed:true,
			collapseMode:'mini',
			floatable:false,
			title:'Compose Mail'
		}
	]
});
